### ISSUE TITLE
Unmatched Reads

### ISSUE THREAD

**Issue by mafeiyang** [NuttyLogic/Demultiplexer#14]
I tried to demultiplex 2 read files with 1 barcode file. The order of the files is 'rbr'. The script worked well and I got the demultiplexed reads for each of my samples. 

However, there was a problem with the unmatched reads. I believe what the script intended to do was to put the unmatched reads from read1 file to unmatched_1.fastq and the unmatched reads from read2 file to unmatched_2.fastq. While the script put the unmatched reads from read1 file to unmatched_2.fastq, leaving unmatched_1.fastq empty and the unmatched reads from read2 file gone. 

Can you do something to correct this?

**Comment by NuttyLogic** [comment]
The bug has been addressed in version 1.0.1.
